# Generated by Django 5.1.6 on 2025-03-09 15:32

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[main.validators.validate_title],
                verbose_name="Заголовок",
            ),
        ),
    ]
